name: Web Development with Cursor AI Bootstrap
description: A comprehensive starter template for web development teams using Cursor AI with optimized agent configurations, MCP integrations, and modern development tools.

# Template repository settings
template:
  name: web-dev-cursor-bootstrap
  description: Bootstrap template for web development with Cursor AI agents
  
# Files to exclude when creating from template
exclude:
  - BOOTSTRAP_SUMMARY.md
  - .cursor/mcp-configs/
  
# Template metadata
metadata:
  category: web-development
  tags:
    - cursor-ai
    - web-development
    - react
    - typescript
    - ai-agents
    - mcp
    - bootstrap
    - template 